### ISSUE TITLE
クラスの役割が正しいのか見直してみよう

### ISSUE THREAD

**Issue by ayaha401** [nkc20206082/PiroroText#1]
![image](https://user-images.githubusercontent.com/75297336/160263100-2d363ceb-4d2a-462c-84fb-fd858f8ef883.png)
現状のクラス間の関係がこうなっていて
矢印が刺さってるものを**知っている**っていう図になってる。一番わかりやすい例はプレゼンターはModelとViewを知っている

見直す箇所は2か所
* Viewでオブジェクトプールをしてる
* Viewでオブジェクトを生成している

# Viewでオブジェクトプールをしてる
Viewの仕事はUIがどんな見た目になるかを制御すること。
なのでViewがオブジェクトプールをするのはちょっと仕事違いになる

# Viewでオブジェクトを生成している
これも上と同様に見た目を制御すること以上の仕事をしてしまってるので仕事違いになっている

# どう直すか
![image](https://user-images.githubusercontent.com/75297336/160263582-3899c168-fb08-4cb6-b75d-52d5ef150742.png)
おそらくこれが一番簡単な方法だと思う
オブジェクトがMVPを全部すでに持っていて、それを丸ごとInstantiateしたりSetActiveしたりする
### 注意
InstantiatedObjの中身のスクリプトとNonInstantiatedObjの中身は同じ。図のために違うスクリプトっぽく見えてるだけ

**Comment by nkc20206082** [comment]
たぶんできた

**Comment by ayaha401** [comment]
すごくいい！設計図通りになってる！閉じますね
