### ISSUE TITLE
DamageTextControllerの修正するといい箇所

### ISSUE THREAD

**Issue by ayaha401** [nkc20206082/PiroroText#2]
**クラスの仕事外のことをやってることは無視して修正するといい箇所を書くよ**

https://github.com/nkc20206082/PiroroText/blob/9b98dd47efe9a1fec1b01d83515820d003dbaf2d/TextMakerPro/Assets/Scripts/DamageTextController.cs#L16

ここの`a`がたぶん透明度の値の変数名だと思うけど`alpha`とかにするといいと思う`a`だけだと何かわからない可能性がある
個人的に`a`だけでもいいと思う場面は
```C#
if(Color.r < 1.0f)
{
    Color.a = 1.0f;
}
```
のように`Color`とかってつけば`r` `g` `b` `a`の一文字が何を表しているのかわかるのでいいと思う

**Comment by nkc20206082** [comment]
aをalphaに変更

**Comment by ayaha401** [comment]
いい感じ！閉じますね
