### ISSUE TITLE
InputEnterの修正するといいと思う箇所

### ISSUE THREAD

**Issue by ayaha401** [nkc20206082/PiroroText#3]
**クラスの仕事外のことをやってることは無視して修正するといい箇所を書くよ**
https://github.com/nkc20206082/PiroroText/blob/9b98dd47efe9a1fec1b01d83515820d003dbaf2d/TextMakerPro/Assets/Scripts/InputEnter.cs#L21

ここの`0.2f`がマジックナンバーになってる。
マジックナンバーを無くすべきかなって思ったけどここまでやる必要性あるのかわからない。ここぐらいならいい気もしてきた

# 修正案
```C#
IEnumerator EnterInterval()
    {
        const  float INTERVAL = 0.2f;
        _enterInterval = true;
        yield return new WaitForSeconds(INTERVAL);
        _enterInterval = false;
    }
```

# ここいいと思った
https://github.com/nkc20206082/PiroroText/blob/9b98dd47efe9a1fec1b01d83515820d003dbaf2d/TextMakerPro/Assets/Scripts/InputEnter.cs#L18
`EnterInterval`って名前いいと思った。インターバルを持たせたいんだなってのが一発でわかった。

**Comment by nkc20206082** [comment]
修正案に変更

**Comment by ayaha401** [comment]
いい感じ。マジックナンバーここまで消す必要性あるのかわからんけど…今回はこんな感じにしておきますかね
