### ISSUE TITLE
TextMakePresenterの修正するといいと思う箇所

### ISSUE THREAD

**Issue by ayaha401** [nkc20206082/PiroroText#5]
https://github.com/nkc20206082/PiroroText/blob/9b98dd47efe9a1fec1b01d83515820d003dbaf2d/TextMakerPro/Assets/Scripts/TextMakePresenter.cs#L8

Awakeってpublicじゃないといけないっけ？publicで公開すべきメソッドじゃない気がする

**Comment by nkc20206082** [comment]
private void Awake()に変更

**Comment by ayaha401** [comment]
OK！閉じますね
