### ISSUE TITLE
TextPoolのメソッド名をわかりやすく命名した方がいいと思う

### ISSUE THREAD

**Issue by ayaha401** [nkc20206082/PiroroText#8]
https://github.com/nkc20206082/PiroroText/blob/b576506e4efeee690a774a41bcd7058bc849f4a8/TextMakerPro/Assets/Scripts/TextPool.cs#L9

このメソッドの仕事はオブジェクトプールで生成するかSetActiveを変えるか？を判断してる処理であってAttackしているわけじゃないからメソッドの名前をもう少し工夫するべきだと思う
これだと何かが攻撃をするのかな？って誤解を招くもとになってしまう

`GenerateTextObj`とか`MakeTextObj`とか作りますよ的な名前でいいんじゃないかな

**Comment by nkc20206082** [comment]
変えます

**Comment by ayaha401** [comment]
変わってた。いい感じ。閉じますね
